# Generated by Django 6.1.1 on 2026-09-25 17:03

import chat.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=chat.models.sticker_path)),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('animated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='sticker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chat.sticker'),
        ),
        migrations.CreateModel(
            name='UserSticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved', models.BooleanField(default=False)),
                ('favorite', models.BooleanField(default=False)),
                ('favorited_at', models.DateTimeField(blank=True, null=True)),
                ('saved_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('sticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='chat.sticker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stickers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'sticker'), name='uniq_user_sticker')],
            },
        ),
    ]
