# Generated by Django 6.1.1 on 2026-09-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_onetimecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimecode',
            name='purpose',
            field=models.CharField(choices=[('password_reset', 'Réinitialisation du mot de passe'), ('login', 'Vérification de connexion')], db_index=True, default='password_reset', max_length=32),
        ),
    ]
