# Generated by Django 6.1.1 on 2026-09-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_pushsubscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='online_count',
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='last_active_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
    ]
