# Generated by Django 6.1.1 on 2026-09-26 14:08

import django.db.models.deletion
import django.utils.timezone
import live.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=80)),
                ('audience', models.CharField(choices=[('public', 'Tout le monde'), ('followers', 'Abonnés uniquement')], default='public', max_length=10)),
                ('status', models.CharField(choices=[('live', 'En direct'), ('ended', 'Terminé')], db_index=True, default='live', max_length=8)),
                ('media_key', models.CharField(default=live.models.media_key, max_length=32, unique=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('host_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('gifts_count', models.PositiveIntegerField(default=0)),
                ('gifts_value', models.PositiveIntegerField(default=0)),
                ('peak_viewers', models.PositiveIntegerField(default=0)),
                ('total_viewers', models.PositiveIntegerField(default=0)),
                ('new_followers', models.PositiveIntegerField(default=0)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lives', to=settings.AUTH_USER_MODEL)),
                ('pinned_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='live.livecomment')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift', models.CharField(choices=[('rose', 'Rose'), ('heart', 'Cœur'), ('fire', 'Flamme'), ('crown', 'Couronne'), ('fireworks', "Feu d'artifice"), ('car', 'Bolide'), ('lion', 'Lion'), ('galaxy', 'Galaxie')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('live', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='live.livestream')),
            ],
        ),
        migrations.AddField(
            model_name='livecomment',
            name='live',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='live.livestream'),
        ),
        migrations.CreateModel(
            name='LiveBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('live', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='live.livestream')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('live', 'user'), name='uniq_live_ban')],
            },
        ),
        migrations.CreateModel(
            name='LiveViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('live', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to='live.livestream')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('live', 'user'), name='uniq_live_viewer')],
            },
        ),
    ]
