# Generated by Django 6.1.1 on 2026-09-26 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0002_livecomment_reply_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liveban',
            options={'verbose_name': 'Exclusion', 'verbose_name_plural': 'Exclusions'},
        ),
        migrations.AlterModelOptions(
            name='livecomment',
            options={'verbose_name': 'Commentaire', 'verbose_name_plural': 'Commentaires'},
        ),
        migrations.AlterModelOptions(
            name='livegift',
            options={'verbose_name': 'Cadeau', 'verbose_name_plural': 'Cadeaux'},
        ),
        migrations.AlterModelOptions(
            name='livestream',
            options={'ordering': ['-started_at'], 'verbose_name': 'Live', 'verbose_name_plural': 'Lives'},
        ),
        migrations.AlterModelOptions(
            name='liveviewer',
            options={'verbose_name': 'Spectateur', 'verbose_name_plural': 'Spectateurs'},
        ),
    ]
